ThreeDPrintMVC/Controllers/PrinterController.cs
using Microsoft.AspNet.Identity;
using Models.PrinterModels;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThreeDPrintMVC.Controllers
{
    
    public class PrinterController : Controller
    {
        // GET: Printer
        [Authorize]
        public ActionResult Index()
        {
            var service = CreatePrinterService();
            var model = service.GetPrinters();
            return View(model);
        }

        public ActionResult Info()
        {
            return View();
        }


        public ActionResult Default()
        {
            var ps = new PrinterService();
            var model = ps.GetPrintersSeed();
            return View(model);
        }

        public ActionResult DefaultDetail(int id)
        {
            var ps = new PrinterService();
            var model = ps.GetPrinterByIdSeed(id);

            return View(model);
        }
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PrinterCreate model)
        {
           

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            HttpPostedFileBase file = Request.Files["ImageData"];
            var service = CreatePrinterService();
            
              
            if(service.CreatePrinter(file,model))
            {
                TempData["SaveResult"] = $"{model.PrinterModel} was created!";
                
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Printer could not be created.");

            return View(model);

        }

        public ActionResult RetrieveImage(int id)
        {
            var s = new PrinterService();
            byte[] cover = s.GetImageFromDataBase(id);
            if(cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        [Authorize]
        public ActionResult Detail(int id)
        {
            var service = CreatePrinterService();

            var entity = service.GetPrinterById(id);

            return View(entity);
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            var srv = CreatePrinterService();

            var detailModel = srv.GetPrinterById(id);
            var editModel = new PrinterEdit { PrinterId = detailModel.PrinterId, CanAutoLevel = detailModel.CanAutoLevel, PrinterModel = detailModel.PrinterModel, HasDualExtruder = detailModel.HasDualExtruder, HasHeatedBed = detailModel.HasHeatedBed, PrinterBand = detailModel.PrinterBrand, CanUpgrade = detailModel.CanUpgrade, HasCamera = detailModel.HasCamera, HasWifi = detailModel.HasWifi, Image = detailModel.Image };
            //has not added img 
            return View(editModel);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PrinterEdit model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if(id!=model.PrinterId)
            {
                ModelState.AddModelError("", "Id does not match");
                return View(model);
            }
            HttpPostedFileBase file = Request.Files["ImageData"];
            var srv = CreatePrinterService();

            if (srv.UpdatePrinter(file,model))
            {
                TempData["SaveResult"] = $"{model.PrinterModel} was Updated!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Nothing has been changed. Change something and save or cancel.");

            return View(model);

        }
        [Authorize]
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var srv = CreatePrinterService();

            var model = srv.GetPrinterById(id);

            return View(model);
        }
        [Authorize]
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePrinter(int id)
        {
            var srv = CreatePrinterService();

            srv.DeletePrinter(id);
            TempData["SaveResult"] = "Printer Deleted!";
            return RedirectToAction("Index");
        }

        
        private PrinterService CreatePrinterService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new PrinterService(userId);
            return service;
        }

    }
}

ThreeDPrintMVC/Controllers/SettingController.cs
using Microsoft.AspNet.Identity;
using Models.SettingModels;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThreeDPrintMVC.Controllers
{
    [Authorize]
    public class SettingController : Controller
    {
        // GET: Setting
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateWPrint(int id)
        {
            var ps = CreatePrinterService();
            var ms = MService();
            var mSelectList = ms.MaterialSelectList();

            if(ms.GetMaterials().Count() == 0)
            {
                TempData["NoMaterial"] = "You need to have at least one material created before adding Custom Settings";
                return RedirectToAction("Create", "Material"); 
            }

            var n = ps.GetPrinterById(id);
            ViewBag.PrinterBrand = n.PrinterBrand;
            ViewBag.PrinterId = n.PrinterId;
            ViewBag.MaterialId = new SelectList(mSelectList, "MaterialId", "MaterialInfo");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateWPrint(SettingCreate model, int id)
        {
            var ps = CreatePrinterService();
            var ms = MService();
            var mSelectList = ms.MaterialSelectList();


            var printer = ps.GetPrinterById(id);
            var pId = printer.PrinterId;
            ViewBag.PrinterId = printer.PrinterId;
            ViewBag.MaterialId = new SelectList(mSelectList, "MaterialId", "MaterialInfo");

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var src = SService();

            if (src.CreateSettingWPrint(model, pId))
            {
                if(printer.HasHeatedBed == false)
                { TempData["NoBed"] = $"Bed temp set to zero because {printer.PrinterBrand} has no heated bed."; };
                TempData["SettingSave"] = $"{model.CustomSettingName} was created!";
                return RedirectToAction("Detail", "Printer", new { id = pId });

            }
            ModelState.AddModelError("", "Setting could not be created");

            return View(model);
        }

        public ActionResult Create()
        {
            var ps = CreatePrinterService();
            var ms = MService();
            var mSelectList = ms.MaterialSelectList();
            var pSelectList = ps.PrinterSelectList();
            if(ps.GetPrinters().Count()==0)
            {
                TempData["NoPrinter"] = "You need to have at least one printer to create Custom Settings";
                return RedirectToAction("Create", "Printer");
            }

            if (ms.GetMaterials().Count() == 0)
            {
                TempData["NoMaterial"] = "You need to have at least one material created before adding Custom Settings";
                return RedirectToAction("Create", "Material");
            }


            ViewBag.MaterialId = new SelectList(mSelectList, "MaterialId", "MaterialInfo");
            ViewBag.PrinterId = new SelectList(pSelectList, "PrinterId", "PrinterInfo");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SettingCreate model)
        {
            var ps = CreatePrinterService();
            var ms = MService();
            var mSelectList = ms.MaterialSelectList();
            var pSelectList = ps.PrinterSelectList();
            ViewBag.MaterialId = new SelectList(mSelectList, "MaterialId", "MaterialInfo");
            ViewBag.PrinterId = new SelectList(pSelectList, "PrinterId", "PrinterInfo");
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var src = SService();

            if (src.CreateSetting(model))
            {
                return RedirectToAction("Detail", "Printer", new { id = model.PrinterId });
                
            }
            return View(model);
        }

        public ActionResult Edit(int settingId, int printerId)
        {
            var ps = CreatePrinterService();
            var ms = MService();
            var mSelectList = ms.MaterialSelectList();
            var pSelectList = ps.PrinterSelectList();
            ViewBag.PrinterId = new SelectList(pSelectList, "PrinterId", "PrinterInfo");
            ViewBag.MaterialId = new SelectList(mSelectList, "MaterialId", "MaterialInfo");

            var srv = SService();
            var setting = srv.GetSettingById(settingId);
            var model = new SettingEdit 
            { 
                CustomSettingName = setting.CustomSettingName, 
                BedTemp = setting.BedTemp, 
                MaterialId = setting.MaterialId, 
                PrinterId = setting.PrinterId, 
                MaterialTemp = setting.MaterialTemp, 
                SettingId = setting.SettingId, 
                Speed = setting.Speed
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int settingId, int printerId, SettingEdit model)
        {
            var ps = CreatePrinterService();
            var ms = MService();
            var pSelectList = ps.PrinterSelectList();
            var mSelectList = ms.MaterialSelectList();
            ViewBag.PrinterId = new SelectList(pSelectList, "PrinterId", "PrinterInfo");
            ViewBag.MaterialId = new SelectList(mSelectList, "MaterialId", "MaterialInfo");

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (settingId != model.SettingId)
            {
                ModelState.AddModelError("", "Id does not match");
                return View(model);
            }

            var srv = SService();
            if (srv.UpdateSetting(model, printerId))
            {
                TempData["SettingUpdate"] = $"You updated {model.CustomSettingName}";
                return RedirectToAction("Detail", "Printer", new { id = model.PrinterId });
            }
            ModelState.AddModelError("", "Setting could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var srv = SService();
            var model = srv.GetSettingById(id);
            return View(model);

        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteSetting(int id)
        {
            var srv = SService();
            var model = srv.GetSettingById(id);
            var name = model.CustomSettingName;
            var printerId = model.PrinterId;
            srv.DeleteSetting(id);
            TempData["SettingSave"] = $"{name} Deleted!";
            return RedirectToAction("Detail", "Printer", new { id = printerId });
        }

        public ActionResult Detail(int id)
        {
            var srv = SService();
            var setting = srv.GetSettingById(id);
            return View(setting);
            //return RedirectToAction("Index", "PrinterController");
        }

        public SettingService SService()
        {
            var user = Guid.Parse(User.Identity.GetUserId());
            var srv = new SettingService(user);
            return srv;
        }

        private PrinterService CreatePrinterService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new PrinterService(userId);
            return service;
        }
        private MaterialService MService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var srv = new MaterialService(userId);
            return srv;

        }

    }
}

ThreeDPrintMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="bg-dark">
    <nav class="navbar navbar-expand-lg fixed-top bg-secondary">
        <div class="container">

            <div class="navbar-brand ">

                @Html.ActionLink("3D Printer", "Index", "Home", null, new { @class = "text-white nav-link" })
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="text-white">Your Stuff</span>
                </button>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item active m-2">@Html.ActionLink("Printers", "Index", "Printer", new { area = "" }, new { @class = "nav-link text-success" })</li>
                        <li class="nav-item m-2">@Html.ActionLink("Materials", "Index", "Material", new { area = "" }, new { @class = "nav-link text-warning" })</li>
                        <li class="nav-item m-2">@Html.ActionLink("Create Settings", "Create", "Setting", new { area = "" }, new { @class = "nav-link text-info" })</li>
                    </ul>
                </div>
            }

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navmenu">
            @if (Request.IsAuthenticated)
            {

                <span class="text-white">Log Off</span>
            }
            else
            {
                <span class="text-white">Login</span>
            }
        </button>

            <div class="collapse navbar-collapse navbar-brand form-inline my-2 my-lg-0 " id="navmenu">
                <div class="row">
                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                        {
                            @Html.AntiForgeryToken()
                            <ul class="nav navbar-nav m-sm-auto nav-item">
                                <li>

                                    @Html.ActionLink($"Welcome Back {User.Identity.Name}", "Index", "Manage", null, new { @class = "nav-link text-white" })
                                </li>
                                <li>
                                    <a class="nav-item nav-link text-white" href="javascript:document.getElementById('logoutForm').submit()">Log off</a>

                                </li>
                            </ul>
                        }

                    }
                    else
                    {

                        @Html.ActionLink("Register", "Register", "Account", null, new { @class = "nav-link text-white" })
                        @Html.ActionLink("Login", "Login", "Account", null, new { @class = "nav-link text-white" })
                    }
                </div>
            </div>
        </div>

    </nav>

    <div class="container body-content mt-5 pt-5">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-white text-center">&copy; @DateTime.Now.Year - 3D Printer Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>