ThreeDPrintMVC/Controllers/MaterialController.cs
using Microsoft.AspNet.Identity;
using Models.Material;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThreeDPrintMVC.Controllers
{
    
    public class MaterialController : Controller
    {
        // GET: Material
        [Authorize]
        public ActionResult Index()
        {
            var srv = MService();
            var model = srv.GetMaterials();
            return View(model);
        }
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Default()
        {
            var ms = new MaterialService();
            var model = ms.GetMaterialsSeed();
            return View(model);
        }

        public ActionResult DefaultDetail(int id)
        {
            var ms = new MaterialService();
            var model = ms.GetMaterialByIdSeed(id);

            return View(model);
        }



        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MaterialCreate model)
        {

            if(!ModelState.IsValid)
            {
                return View(model);
            }

            HttpPostedFileBase file = Request.Files["ImageData"];
            var srv = MService();

            if(srv.CreateMaterial(file,model))
            {
                TempData["SaveResult"] = $"{model.MaterialBrand} Created!";
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Info()
        {
            return View();
        }

        
        public ActionResult RetrieveMImage(int id)
        {
            
            var mService = new MaterialService();
            byte[] cover = mService.GetImageFromDataBase(id);
            
            if(cover!= null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }

        }

        [Authorize]
        public ActionResult Detail(int id)
        {
            var srv = MService();
            var entity = srv.GetMaterialById(id);
            return View(entity);
        }
        [Authorize]
        public ActionResult Edit(int id)
        {
            var srv = MService();
            var edit = srv.GetMaterialById(id);
            var model = new MaterialEdit { MaterialId = edit.MaterialId, Color = edit.Color, MaterialBrand = edit.MaterialBrand, MaterialType = edit.MaterialType, Image = edit.Image };
            return View(model);

        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MaterialEdit model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if(id != model.MaterialId)
            {
                ModelState.AddModelError("", "Id Mismatch");
                    return View(model); }

            HttpPostedFileBase file = Request.Files["ImageData"];
            var svr = MService();

            if (svr.UpdateMaterial(file,model))
            {
                TempData["SaveResult"] = $"{model.MaterialBrand} Updated!";
                return RedirectToAction("Index");
            }

            return View(model);
        }
        [Authorize]
        public ActionResult Delete(int id)
        {
            var srv = MService();
            var model = srv.GetMaterialById(id);
            return View(model);
        }
        [Authorize]
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteMaterial(int id)
        {
            var srv = MService();
            var model = srv.GetMaterialById(id);
            var name = model.MaterialBrand;
            srv.DeleteMaterial(id);
            TempData["SaveResult"] = $"{name} Deleted!";
            return RedirectToAction("Index");
        }

        private MaterialService MService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var srv = new MaterialService(userId);
            return srv;

        }

    }
}

ThreeDPrintMVC/Views/Material/Create.cshtml
@model Models.Material.MaterialCreate

@{
    ViewBag.Title = "Create";
}

<h2 class="text-white p-2 rounded-pill"style="background-image:url(../../Content/img/yellow.jpeg)">Create New Material</h2>

@if (TempData.ContainsKey("NoMaterial"))
{
    <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>&times;</span>
        </button>
        @TempData["NoMaterial"]
    </div>
}


@using (Html.BeginForm("Create", "Material", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="text-white form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="col">



            <div class="form-group">
                @Html.LabelFor(model => model.MaterialBrand, htmlAttributes: new { @class = "control-label col-md-2" })
                <div >
                    @Html.EditorFor(model => model.MaterialBrand, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaterialBrand, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="row">

                @Html.LabelFor(model => model.MaterialType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EnumDropDownListFor(model => model.MaterialType, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaterialType, "", new { @class = "text-danger" })
                </div>
                </div>

            <div class="row">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" />
                </div>
            </div>

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                <input type="button" value="Cancel" class="btn btn-secondary" onclick="goPrev()" />
                <script>
                    function goPrev() { window.history.back(); }
                </script>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ThreeDPrintMVC/Views/Material/Default.cshtml
@model IEnumerable<Models.Material.MaterialListItem>

@{
    ViewBag.Title = "Default";
}




<div class="row d-flex justify-content-between p-3 mb-3 rounded-pill" style="background-image:url(../../Content/img/White.jpeg)">

    <h2 class="text-white">Material Examples</h2>
    <div class="row mr-1">

        <div class="ml-3">
            <input type="button" value="Add Your Own Material" class="btn btn-primary btn-lg" onclick="window.location = '@Url.Action("Create")'" />
        </div>


    </div>

</div>



<div class="d-flex flex-lg-row flex-column flex-wrap align-items-md-center justify-content-lg-center">
    @foreach (var item in Model)
    {


        <div class="col-2 p-2 mr-4 card text-warning bg-dark border-warning mb-3" style="max-width: 20rem;">
            <div class="card-header bg-secondary text-light">@Html.DisplayFor(Modelitem => item.MaterialBrand)</div>
            @if (item.Image != null && item.Image.Count() > 0)
            {
                <img class="card-img-top mt-1" height="150" width="150" src="/Material/RetrieveMImage/@item.MaterialId" alt="" />

            }
            else
            {
                <img class="card-img-top mt-1" src="~/Content/img/nomaterial.png" />
            }
            <div class="card-body bg-dark">

                <p class="card-text"> @Html.DisplayFor(Modelitem => item.MaterialType)</p>

            </div>
            <div class="d-table-row card-footer bg-secondary">
               

                <input type="button" value="Detail" class="btn btn-dark btn-sm btn-block mt-1" onclick="window.location = '@Url.Action("DefaultDetail", new {id = item.MaterialId})'" />

            </div>
        </div>

    }
</div>


<div class="ml-3">
    <input type="button" value="Home" class="btn btn-secondary btn-lg btn-block" onclick="window.location = '@Url.Action("Index", "Home")'" />
</div>

ThreeDPrintMVC/Views/Material/DefaultDetail.cshtml
@model Models.Material.MaterialDetail

@{
    ViewBag.Title = "DefaultDetail";
}



<div class="d-flex justify-content-around">
    <div>

        <h2 class="text-dark p-3 rounded-pill"style="background-image:url(../../Content/img/White.jpeg)">@Model.MaterialBrand.ToString():</h2>
        <div class="card text-warning bg-dark border-warning mb-3 p-2" style="max-width: 20rem;">
            <div class="card-header bg-secondary text-light">Material Info:</div>
            @if (Model.Image != null)
            {
                <img class="card-img-top mt-1" src="/Material/RetrieveMImage/@Model.MaterialId" alt="" />

            }
            <div class="card-body ">
                <p class="card-title">@Html.DisplayNameFor(model => model.MaterialBrand): @Html.DisplayFor(model => model.MaterialBrand)</p>
                <p class="card-text">@Html.DisplayNameFor(model => model.MaterialType):  @Html.DisplayFor(model => model.MaterialType)</p>
                <p class="card-text">@Html.DisplayNameFor(model => model.Color):  @Html.DisplayFor(model => model.Color)</p>

            </div>
            <div class="card-footer bg-secondary">


                <input type="button" value="Back to Material" class="btn btn-dark btn-block" onclick="window.location= '@Url.Action("Default", "Material")'" />
            </div>
        </div>
    </div>


    @if (Model.MaterialType.ToString() == "PETG")
    {
        <div>
            <h2 class="text-dark p-3 rounded-pill"style="background-image:url(../../Content/img/White.jpeg)">General Info:</h2>
            <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                <div class="bg-dark card-header h5">PETG</div>
                <div class="card-body">

                    <p class="card-text">More flexible than PLA or ABS. Considered Durable</p>
                    <p>Recommended Extruder Temp: 220-235 °C</p>
                    <p>Recommended Bed Temp: None Needed</p>
                    <p>Density: 1270 (Kg/M<sub>3</sub>)</p>
                </div>
                <div class="card-footer bg-dark">
                    <input type="button" value="Learn More" class="btn btn-block btn-outline-secondary" onclick="window.location= '@Url.Action("Info", "Material")'" />

                </div>
            </div>
        </div>
    }

    @if (Model.MaterialType.ToString() == "PLA")
    {

        <div>
            <h2 class="text-dark p-3 rounded-pill" style="background-image:url(../../Content/img/White.jpeg)">General Info:</h2>
            <div class="card text-white bg-info mb-3 " style="max-width: 18rem;">
                <div class="bg-dark card-header h5">PLA</div>
                <div class="card-body">
                    <p class="card-text">Easy to print and Biodegradable through only in very specific conditions.</p>
                    <p>Recommended Extruder Temp: 180-230 °C</p>
                    <p>Recommended Bed Temp: 60-80 °C</p>
                    <p>Density: 1240 (Kg/M<sub>3</sub>)</p>
                </div>
                <div class="card-footer bg-dark">
                    <input type="button" value="Learn More" class="btn btn-block btn-outline-secondary" onclick="window.location= '@Url.Action("Info", "Material")'" />
                </div>
            </div>
        </div>
    }

    @if (Model.MaterialType.ToString() == "ABS")
    {

        <div>
            <h2 class="text-dark p-3 rounded-pill" style="background-image:url(../../Content/img/White.jpeg)">General Info:</h2>
            <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                <div class="bg-dark card-header h5">ABS</div>
                <div class="card-body">
                    <p class="card-text">Durable and impact resitant.</p>
                    <p>Recommended Extruder Temp: 210-250 °C</p>
                    <p>Recommended Bed Temp: 50-100 °C</p>
                    <p>Density: 1010 (Kg/M<sub>3</sub>)</p>
                </div>
                <div class="card-footer bg-dark">
                    <input type="button" value="Learn More" class="btn btn-block btn-outline-secondary" onclick="window.location= '@Url.Action("Info", "Material")'" />
                </div>
            </div>
        </div>
    }

    @if (Model.MaterialType.ToString() == "PVA")
    {

        <div>
            <h2 class="text-dark p-3 rounded-pill" style="background-image:url(../../Content/img/White.jpeg)">General Info:</h2>
            <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                <div class="bg-dark card-header h5">PVA</div>
                <div class="card-body">
                    <p class="card-text">Dissolvable, water soluble, biodegradable, and oil resistant.</p>
                    <p>Recommended Extruder Temp: 180-230 °C</p>
                    <p>Recommended Bed Temp: None Needed</p>
                    <p>Density: 1.19 (g/cm<sub>3</sub>)</p>
                </div>
                <div class="card-footer bg-dark">
                    <input type="button" value="Learn More" class="btn btn-block btn-outline-secondary" onclick="window.location= '@Url.Action("Info", "Material")'" />
                </div>
            </div>
        </div>
    }

    @if (Model.MaterialType.ToString() == "Nylon")
    {

        <div>
            <h2 class="text-dark p-3 rounded-pill" style="background-image:url(../../Content/img/White.jpeg)">General Info:</h2>
            <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                <div class="bg-dark card-header h5">Nylon</div>
                <div class="card-body">
                    <p class="card-text">Strong, flexible, and durable.</p>
                    <p>Recommended Extruder Temp: 220-260 °C</p>
                    <p>Recommended Bed Temp: 50-100 °C</p>
                    <p>Density: 1020 (Kg/M<sub>3</sub>)</p>
                </div>
                <div class="card-footer bg-dark">
                    <input type="button" value="Learn More" class="btn btn-block btn-outline-secondary" onclick="window.location= '@Url.Action("Info", "Material")'" />
                </div>
            </div>
        </div>
    }


</div>

ThreeDPrintMVC/Views/Material/Delete.cshtml
@model Models.Material.MaterialDetail

@{
    ViewBag.Title = "Delete";
}

<h2 class="text-white p-3 rounded-pill"style="background-image:url(../../Content/img/yellow.jpeg)" >Delete @Model.MaterialBrand.ToString()</h2>

<h3 class="text-white">Are you sure you want to delete this?</h3>
<div class="d-flex justify-content-center">
    <div>
        <div class="card text-danger bg-dark border-danger mb-3 p-2" style="max-width: 20rem;">
            <div class="card-header bg-secondary text-light">Material Info:</div>
            @if (Model.Image != null && Model.Image.Count() > 0)
            {
                <img class="card-img-top mt-1" src="/Material/RetrieveMImage/@Model.MaterialId" alt="" />

            }
            else
            {
                <img class="card-img-top mt-1" width="300" height="300" src="~/Content/img/nomaterial.png" />
            }
            <div class="card-body ">
                <p class="card-title">@Html.DisplayNameFor(model => model.MaterialBrand): @Html.DisplayFor(model => model.MaterialBrand)</p>
                <p class="card-text">@Html.DisplayNameFor(model => model.MaterialType):  @Html.DisplayFor(model => model.MaterialType)</p>
                <p class="card-text">@Html.DisplayNameFor(model => model.Color):  @Html.DisplayFor(model => model.Color)</p>

            </div>
            <div class="card-footer bg-secondary">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="col-md-offset-1 col-md-11 d-flex justify-content-between ">
                        <input type="submit" value="Delete" class="btn btn-danger" />

                        <input type="button" value="Cancel" class="btn btn-light" onclick="goPrev()" />
                        <script>
                            function goPrev() { window.history.back(); }
                        </script>
                    </div>
                }


            </div>
        </div>

    </div>
</div>

ThreeDPrintMVC/Views/Material/Detail.cshtml
@model Models.Material.MaterialDetail

@{
    ViewBag.Title = "Detail";
}



<div class="d-flex justify-content-around" >
    <div>

        <h2 class="text-white p-3 rounded-pill" style="background-image:url(../../Content/img/yellow.jpeg)">@Model.MaterialBrand.ToString():</h2>
        <div class="card text-warning bg-dark border-warning mb-3 p-2" style="max-width: 20rem;">
            <div class="card-header bg-secondary text-light">Material Info:</div>
            @if (Model.Image != null && Model.Image.Count() > 0)
            {
                <img class="card-img-top mt-1" src="/Material/RetrieveMImage/@Model.MaterialId" width="300" height="300" alt="" />

            }
            else
            {
                <img class="card-img-top mt-1" src="~/Content/img/nomaterial.png" width="300" height="300" />
            }
            <div class="card-body ">
                <p class="card-title">@Html.DisplayNameFor(model => model.MaterialBrand): @Html.DisplayFor(model => model.MaterialBrand)</p>
                <p class="card-text">@Html.DisplayNameFor(model => model.MaterialType):  @Html.DisplayFor(model => model.MaterialType)</p>
                <p class="card-text">@Html.DisplayNameFor(model => model.Color):  @Html.DisplayFor(model => model.Color)</p>

            </div>
            <div class="card-footer bg-secondary">

                <div class="row justify-content-around">
                    <input type="button" value="Edit" class="btn btn-warning" onclick="window.location= '@Url.Action("Edit", "Material", new {id = Model.MaterialId}, null )'" />

                    <input type="button" value="Delete" class="btn btn-outline-danger" onclick="window.location= '@Url.Action("Delete", "Material", new {id = Model.MaterialId})'" />
                </div>
                <input type="button" value="Back to Material" class="btn btn-dark btn-block mt-1" onclick="window.location= '@Url.Action("Index", "Material")'" />
            </div>
        </div>
    </div>


    @if (Model.MaterialType.ToString() == "PETG")
    {
        <div>
            <h2 class="text-dark rounded-pill p-3" style="background-image:url(../../Content/img/White.jpeg)">General Info:</h2>
            <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                <div class="bg-dark card-header h5">PETG</div>
                <div class="card-body">

                    <p class="card-text">More flexible than PLA or ABS. Considered Durable</p>
                    <p>Recommended Extruder Temp: 220-235 °C</p>
                    <p>Recommended Bed Temp: None Needed</p>
                    <p>Density: 1270 (Kg/M<sub>3</sub>)</p>
                </div>
                <div class="card-footer bg-dark">
                    <input type="button" value="Learn More" class="btn btn-block btn-outline-secondary" onclick="window.location= '@Url.Action("Info", "Material")'" />

                </div>
            </div>
        </div>
    }

    @if (Model.MaterialType.ToString() == "PLA")
    {

        <div>
            <h2 class="text-dark rounded-pill p-3" style="background-image:url(../../Content/img/White.jpeg)">General Info:</h2>
            <div class="card text-white bg-info mb-3 " style="max-width: 18rem;">
                <div class="bg-dark card-header h5">PLA</div>
                <div class="card-body">
                    <p class="card-text">Easy to print and Biodegradable through only in very specific conditions.</p>
                    <p>Recommended Extruder Temp: 180-230 °C</p>
                    <p>Recommended Bed Temp: 60-80 °C</p>
                    <p>Density: 1240 (Kg/M<sub>3</sub>)</p>
                </div>
                <div class="card-footer bg-dark">
                    <input type="button" value="Learn More" class="btn btn-block btn-outline-secondary" onclick="window.location= '@Url.Action("Info", "Material")'" />
                </div>
            </div>
        </div>
    }

    @if (Model.MaterialType.ToString() == "ABS")
    {

        <div>
            <h2 class="text-dark rounded-pill p-3" style="background-image:url(../../Content/img/White.jpeg)">General Info:</h2>
            <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                <div class="bg-dark card-header h5">ABS</div>
                <div class="card-body">
                    <p class="card-text">Durable and impact resitant.</p>
                    <p>Recommended Extruder Temp: 210-250 °C</p>
                    <p>Recommended Bed Temp: 50-100 °C</p>
                    <p>Density: 1010 (Kg/M<sub>3</sub>)</p>
                </div>
                <div class="card-footer bg-dark">
                    <input type="button" value="Learn More" class="btn btn-block btn-outline-secondary" onclick="window.location= '@Url.Action("Info", "Material")'" />
                </div>
            </div>
        </div>
    }

    @if (Model.MaterialType.ToString() == "PVA")
    {

        <div>
            <h2 class="text-dark rounded-pill p-3" style="background-image:url(../../Content/img/White.jpeg)">General Info:</h2>
            <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                <div class="bg-dark card-header h5">PVA</div>
                <div class="card-body">
                    <p class="card-text">Dissolvable, water soluble, biodegradable, and oil resistant.</p>
                    <p>Recommended Extruder Temp: 180-230 °C</p>
                    <p>Recommended Bed Temp: None Needed</p>
                    <p>Density: 1.19 (g/cm<sub>3</sub>)</p>
                </div>
                <div class="card-footer bg-dark">
                    <input type="button" value="Learn More" class="btn btn-block btn-outline-secondary" onclick="window.location= '@Url.Action("Info", "Material")'" />
                </div>
            </div>
        </div>
    }

    @if (Model.MaterialType.ToString() == "Nylon")
    {

        <div>
            <h2 class="text-dark rounded-pill p-3" style="background-image:url(../../Content/img/White.jpeg)">General Info:</h2>
            <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                <div class="bg-dark card-header h5">Nylon</div>
                <div class="card-body">
                    <p class="card-text">Strong, flexible, and durable.</p>
                    <p>Recommended Extruder Temp: 220-260 °C</p>
                    <p>Recommended Bed Temp: 50-100 °C</p>
                    <p>Density: 1020 (Kg/M<sub>3</sub>)</p>
                </div>
                <div class="card-footer bg-dark">
                    <input type="button" value="Learn More" class="btn btn-block btn-outline-secondary" onclick="window.location= '@Url.Action("Info", "Material")'" />
                </div>
            </div>
        </div>
    }


</div>

ThreeDPrintMVC/Views/Material/Edit.cshtml
@model Models.Material.MaterialEdit

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-white p-3 rounded-pill" style="background-image:url(../../Content/img/yellow.jpeg)">Update @Model.MaterialBrand</h2>


@using (Html.BeginForm("Edit", "Material", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="col text-white">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaterialId)



        <div class="col">


            <div class="form-group">
                @Html.LabelFor(model => model.MaterialBrand, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="">
                    @Html.EditorFor(model => model.MaterialBrand, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaterialBrand, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="">
                    @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                <div class="row">
                    @Html.LabelFor(model => model.MaterialType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.MaterialType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaterialType, "", new { @class = "text-danger" })
                    </div>
                </div>



                
                <div class="row">
                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="ImageData" id="ImageData" onchange="filecheck(this);" />
                    </div>
                </div>


                <div class="row">
                    <p class="col-md-2">Current Image</p>
                    @if (Model.Image != null && Model.Image.Length > 0)
                    {

                        <div class="ml-md-2"><img class="img-fluid" width="150" height="150" src="/Material/RetrieveMImage/@Model.MaterialId" /></div>
                    }
                    else
                    {
                        <div class="ml-md-2"><p>None</p></div>
                    }
                </div>




            </div>

        </div>
    <div class="row">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />

            <input type="button" value="Cancel" class="btn btn-secondary" onclick="goPrev()" />
            <script>
                function goPrev() { window.history.back(); }
            </script>
        </div>
    </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ThreeDPrintMVC/Views/Material/Index.cshtml
@model IEnumerable<Models.Material.MaterialListItem>

@{
    ViewBag.Title = "Index";
}

<div class="row d-flex justify-content-between p-3 rounded-pill" style="background-image:url(../../Content/img/yellow.jpeg)">

    <h2 class="text-white">Your Material</h2>
    <div class="ml-3 mr-1">
        <input type="button" value="Add New Material" class="btn btn-primary btn-lg" onclick="window.location = '@Url.Action("Create")'" />
    </div>
</div>

@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade-in mt-1" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}
<div>

</div>

<br/>



<div class="d-flex flex-lg-row flex-column flex-wrap align-items-md-center justify-content-lg-center">
    @foreach (var item in Model)
    {


        <div class="col-2 p-2 mr-4 card text-warning bg-dark border-warning mb-3" style="max-width: 20rem;">
            <div class="card-header bg-secondary text-light">@Html.DisplayFor(Modelitem => item.MaterialBrand)</div>
            @if (item.Image != null && item.Image.Count() > 0)
            {
                <img class="card-img-top mt-1" src="/Material/RetrieveMImage/@item.MaterialId" alt="" />

            }
            else
            {
                <img class="card-img-top mt-1" src="~/Content/img/nomaterial.png" />
            }
            <div class="card-body bg-dark">

                <p class="card-text"> @Html.DisplayFor(Modelitem => item.MaterialType)</p>

            </div>
            <div class="d-table-row card-footer bg-secondary">
                <div class="row justify-content-around">

                    <input type="button" value="Edit" class="btn btn-warning btn-sm" onclick="window.location = '@Url.Action("Edit", new {id = item.MaterialId})'" />

                    <input type="button" value="Delete" class="btn btn-outline-danger btn-sm" onclick="window.location = '@Url.Action("Delete", new {id = item.MaterialId})'" />

                </div>


                <input type="button" value="Detail" class="btn btn-dark btn-sm btn-block mt-1" onclick="window.location = '@Url.Action("Detail", new {id = item.MaterialId})'" />

            </div>
        </div>

    }
</div>












    <div class="ml-3">
        <input type="button" value="Home" class="btn btn-secondary btn-lg btn-block" onclick="window.location = '@Url.Action("Index", "Home")'" />
    </div>